#Database
POSTGRESQL_USERNAME : user
POSTGRESQL_PASSWORD : letmein
POSTGRESQL_HOST : 192.168.1.216
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: docdatabase

#SERVER
CONTAINER_PORT : 8085
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST : smtp.gamil.com
EMAIL_PORT : 587
EMAIL_ID:
EMAIL_PASSWORD:
VERIFY_EMAIL_HOST: http://localhost:8085